networks:
  nginx_network:
    external: true

services:
  db:
    image: docker.io/mariadb:11.5.2
    container_name: passbolt-db
    restart: unless-stopped
    networks:
      nginx_network:
        ipv4_address: 192.168.200.61
    dns:
      - ${DNS}
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - TZ=${TZ}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=passbolt
      - MYSQL_USER=passbolt
      - MYSQL_PASSWORD_FILE=/run/secrets/secret_mysql_pw
    security_opt:
      - no-new-privileges:true
    secrets:
      - secret_mysql_pw

  passbolt:
    image: docker.io/passbolt/passbolt:4.9.1-1-ce
    container_name: passbolt
    restart: unless-stopped
    networks:
      nginx_network:
        ipv4_address: 192.168.200.60
    dns:
      - ${DNS}
    expose:
      - 80
    #volumes:
    #  - ./gpg:/etc/passbolt/gpg
    #  - ./jwt:/etc/passbolt/jwt
    environment:
      - TZ=${TZ}
      #- APP_BASE=/passbolt
      - APP_FULL_BASE_URL=https://passbolt.maku.local
      - DATASOURCES_DEFAULT_HOST=db
      - DATASOURCES_DEFAULT_USERNAME=passbolt
      - DATASOURCES_DEFAULT_PASSWORD_FILE=/run/secrets/secret_mysql_pw
      - DATASOURCES_DEFAULT_DATABASE=passbolt
      - EMAIL_DEFAULT_FROM_NAME=Maku Passbolt
      - EMAIL_DEFAULT_FROM=<HIDDEN_DATA>
      - EMAIL_TRANSPORT_DEFAULT_HOST=smtp.gmail.com
      - EMAIL_TRANSPORT_DEFAULT_PORT=587
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=<HIDDEN_DATA>
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=<HIDDEN_DATA>
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
    security_opt:
      - no-new-privileges:true
    command: ["/usr/bin/wait-for.sh", "-t", "0", "db:3306", "--", "/docker-entrypoint.sh"]
    depends_on:
      - db
    secrets:
      - secret_mysql_pw

secrets:
   secret_mysql_pw:
     file: ./secrets/secret_mysql_pw.txt

###### CONFIGURATION ######

#up...
#docker compose -f passbolt-docker-compose.yml exec passbolt su -m -c "/usr/share/php/passbolt/bin/cake passbolt register_user --username <HIDDEN_DATA> --first-name Mateusz --last-name Maczewski --role admin" -s /bin/sh www-data
#enter to link in prompt
#download browser extension
#password:<HIDDEN_DATA>
#download: passbolt-recovery-kit.txt, passbolt_public.txt, passbolt_private.txt
#security token: <HIDDEN_DATA>
#down...
#up...
#<ADDR>/recover
