networks:
  nginx_network:
    external: true

services:
  #https://github.com/seriousm4x/UpSnap
  upsnap:
    image: ghcr.io/seriousm4x/upsnap:4.3.2 # images are also available on docker hub: seriousm4x/upsnap:4
    container_name: upsnap
    restart: unless-stopped
    user: ${UID}:${GID}
    network_mode: host
    dns:
      - ${DNS}
    volumes:
      - ./data:/app/pb_data
    environment:
      - TZ=${TZ}
      - UPSNAP_INTERVAL=@every 10s # Sets the interval in which the devices are pinged
    #  - UPSNAP_SCAN_RANGE=192.168.1.0/24 # Scan range is used for device discovery on local network
    #  - UPSNAP_SCAN_TIMEOUT=500ms # Scan timeout is nmap's --host-timeout value to wait for devices (https://nmap.org/book/man-performance.html)
      - UPSNAP_PING_PRIVILEGED=false # Set to false if you don't have root user permissions
      - UPSNAP_WEBSITE_TITLE=Maku Wake On LAN # Custom website title
    security_opt:
      - no-new-privileges:true
    # # you can change the listen ip:port inside the container like this:
    # entrypoint: /bin/sh -c "./upsnap serve --http 0.0.0.0:5000"
    # healthcheck:
    #   test: curl -fs "http://localhost:5000/api/health" || exit 1
    #   interval: 10s
    # # or install custom packages for shutdown
    # entrypoint: /bin/sh -c "apk update && apk add --no-cache <YOUR_PACKAGE> && rm -rf /var/cache/apk/* && ./upsnap serve --http 0.0.0.0:8090"
