networks:
  nginx_network:
    external: true

services:
  #https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.18
    container_name: mosquitto
    restart: unless-stopped
    networks:
      nginx_network:
        ipv4_address: 192.168.200.150
    dns:
      - ${DNS}
    expose:
      - 1883
      - 9001
    volumes:
      - ./mosquitto-config:/mosquitto/config
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-log:/mosquitto/log
    environment:
      - TZ=${TZ}
    security_opt:
      - no-new-privileges:true

  #https://hub.docker.com/r/koenkk/zigbee2mqtt
  zigbee2mqtt:
    image: docker.io/koenkk/zigbee2mqtt:1.40.1
    container_name: zigbee2mqtt
    restart: unless-stopped
    networks:
      nginx_network:
        ipv4_address: 192.168.200.151
    dns:
      - ${DNS}
    expose:
      - 8080
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - "/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230508094110-if00:/dev/zigbee"
    environment:
      - TZ=${TZ}
    security_opt:
      - no-new-privileges:true
    depends_on:
      - mosquitto

###### CONFIGURATION ######

#cat >> ./mosquitto-config/mosquitto.conf << "EOF"
#persistence true
#persistence_location /mosquitto/data/
#log_dest file /mosquitto/log/mosquitto.log
#log_type all
#allow_anonymous true
#listener 1883
#EOF

#docker exec -it mosquitto /bin/sh

#mosquitto_passwd -c /mosquitto/config/password.txt mqtt    -->  mqtt /<HIDDEN_DATA>

#cat > ./mosquitto-config/mosquitto.conf << "EOF"
#persistence true
#persistence_location /mosquitto/data/
#log_dest file /mosquitto/log/mosquitto.log
#log_type all
#allow_anonymous false
#password_file /mosquitto/config/password.txt
#listener 1883
#EOF

#cat > ./zigbee2mqtt-data/configuration.yaml << "EOF"
#homeassistant: true
#permit_join: true
#frontend: true
#mqtt:
#  base_topic: zigbee2mqtt
#  server: mqtt://mqtt:1883
#  user: mqtt
#  password: <HIDDEN_DATA>
#serial:
#  port: /dev/zigbee
#  adapter: ezsp
#advanced:
#  homeassistant_legacy_entity_attributes: false
#  legacy_api: false
#  legacy_availability_payload: false
#device_options:
#  legacy: false
#EOF

#docker compose --file zigbee2mqtt-compose.yml restart
